name: Container Scan

on:
  schedule:
    - cron: '0 3 * * 1'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    name: Scan container image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Verify GitHub Advanced Security availability
        uses: actions/github-script@v7
        with:
          script: |
            const { security_and_analysis } = (await github.rest.repos.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })).data;
            const status = security_and_analysis?.advanced_security?.status;
            if (status !== 'enabled') {
              core.setFailed('GitHub Advanced Security is not enabled for this repository.');
            }

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build container image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          push: false
          tags: local/p2p-video-sharing-client:latest

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.19.0
        with:
          scan-type: image
          image-ref: local/p2p-video-sharing-client:latest
          format: sarif
          output: trivy-results.sarif
          vuln-type: os,library
          severity: CRITICAL,HIGH

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

      - name: Upload Trivy report artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results
          path: trivy-results.sarif
